# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoList+server' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodoList+server
  pod 'Alamofire'

  target 'TodoList+serverTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodoList+serverUITests' do
    # Pods for testing
  end

end
